<a href="https://colab.research.google.com/github/Ekansh0801/Large-Language-Model/blob/main/Building_LLM_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building Large Language Model from Scratch

## Stage - 1 : Data Preprocessing

In [9]:
# Loading the Dataset

with open('the-verdict.txt', 'r', encoding='utf-8') as file:
  raw_text = file.read()

print(len(raw_text))

20479


In [10]:
# Printing first 100 characters

print(raw_text[:100])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g


### Implementing Tokenization

#### step - 1: Creating Tokens

In [11]:
# Importing re library for tokenization purpose
import re

# splitting the text on any special character or -- or space
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)

# storing only non whitespace characters
preprocessed = [item.strip() for item in preprocessed if item.strip()]

print(len(preprocessed))

print(preprocessed[:100])

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--']


#### Step - 2: assigning token ID's

In [12]:
all_words = sorted(set(preprocessed))

vocab_size = len(all_words)
print(vocab_size)

1130


In [13]:
vocab = {token:integer for integer, token in enumerate(all_words)}
# print(vocab)

In [14]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


#### Implementing a Tokenizer class

In [15]:
class simpleTokenizerV1:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {value : key for key, value in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [token.strip() for token in preprocessed if token.strip()]

    ids = [self.str_to_int[token] for token in preprocessed]
    return ids

  def decode(self, ids):
    sentence = " ".join([self.int_to_str[id] for id in ids])
    sentence = re.sub(r'\s+([,.?!"()\'])', r'\1', sentence)
    return sentence

In [16]:
# check if the class is working succesfully

texty = """Well!--even through the prism of Hermia's tears I felt able to face the fact with equanimity.
Poor Jack Gisburn! The women had made him--it was fitting that they should mourn him.
Among his own sex fewer regrets were heard, and in his own trade hardly a murmur.
Professional jealousy? Perhaps. If it were, the honour of the craft was vindicated by little Claude Nutley,
who, in all good faith, brought out in the Burlington a very handsome "obituary" on Jack--one of those
showy articles stocked with random technicalities that I have heard (I won't say by whom) compared to
Gisburn's painting. And so--his resolve being apparently irrevocable--the discussion gradually
died out, and, as Mrs. Thwing had predicted, the price of "Gisburns" went up."""

tokenizer = simpleTokenizerV1(vocab)

ids = tokenizer.encode(texty)
print(ids)


[108, 0, 6, 399, 1007, 988, 795, 722, 50, 2, 850, 976, 53, 436, 117, 1016, 418, 988, 420, 1108, 395, 7, 80, 57, 38, 0, 93, 1112, 514, 654, 546, 6, 585, 1077, 444, 987, 994, 879, 687, 546, 7, 13, 549, 742, 872, 438, 829, 1088, 536, 5, 157, 568, 549, 742, 1026, 528, 115, 694, 7, 81, 589, 10, 79, 7, 54, 585, 1088, 5, 988, 553, 722, 988, 299, 1077, 1067, 241, 635, 26, 72, 5, 1097, 5, 568, 145, 500, 425, 5, 234, 738, 568, 988, 21, 115, 1065, 523, 1, 717, 1, 727, 57, 6, 729, 722, 1001, 884, 175, 927, 1108, 817, 977, 987, 53, 530, 536, 3, 53, 1113, 2, 970, 856, 241, 1099, 4, 281, 1016, 38, 2, 850, 748, 7, 14, 908, 6, 549, 838, 213, 165, 583, 6, 988, 345, 505, 337, 738, 5, 157, 5, 177, 67, 7, 100, 514, 786, 5, 988, 792, 722, 1, 39, 1, 1087, 1051, 7]


In [17]:
decoded_text = tokenizer.decode(ids)
print(decoded_text[:100])

Well! -- even through the prism of Hermia' s tears I felt able to face the fact with equanimity. Poo


In [18]:
# unknown_str = "milk is healthy and is a good source of protien."

# n_ids = tokenizer.encode(unknown_str)
# print(n_ids)

#### error because now we used an text with unknown words so it is not stored in the vocab hence error is thrown

#### Hence we will now extend unknown token and endoftext token also

In [19]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|unk|>", "<|endoftext|>"])

In [20]:
# updated vocab as it now includes unknown and endoftext also

vocab = { index:token for token, index in enumerate(all_tokens)}

for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|unk|>', 1130)
('<|endoftext|>', 1131)


### Updating tokenizer class

In [21]:
class simpleTokenizerV2:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {value : key for key, value in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [token.strip() for token in preprocessed if token.strip()]

    preprocessed = [item if item in self.str_to_int else '<|unk|>' for item in preprocessed]

    ids = [self.str_to_int[token] for token in preprocessed]
    return ids

  def decode(self, ids):
    sentence = " ".join([self.int_to_str[id] for id in ids])
    sentence = re.sub(r'\s+([,.?!"()\'])', r'\1', sentence)
    return sentence

#### checking the new tokenizer class

In [22]:
# unknown_str = "milk is healthy and is a good source of protien."

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

tokenizer2 = simpleTokenizerV2(vocab)
n_ids = tokenizer2.encode(text)
print(n_ids)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.
[1130, 5, 355, 1126, 628, 975, 10, 1131, 55, 988, 956, 984, 722, 988, 1130, 7]


In [23]:
dec_text = tokenizer2.decode(n_ids)
print(dec_text)

<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


### Byte Pair Encoding

In [24]:
pip install tiktoken

In [25]:
import importlib
import tiktoken

print("Tiktoken version:", importlib.metadata.version("tiktoken"))

Tiktoken version: 0.14.0


#### using the GPT-2 tokenizer

In [26]:
tokenizer = tiktoken.get_encoding("gpt2")

<div class="alert alert-block alert-success">
The usage of this tokenizer is similar to SimpleTokenizerV2 we implemented previously via
an encode method:</div>



In [27]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


<div class="alert alert-block alert-success">
We can then convert the token IDs back into text using the decode method, similar to our
SimpleTokenizerV2 earlier:</div>


In [28]:
strings = tokenizer.decode(integers)

print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


**Let us take another simple example to illustrate how the BPE tokenizer deals with unknown tokens**

In [29]:
integers = tokenizer.encode("Swati will be mine!!!")

print(integers)

strings = tokenizer.decode(integers)
print(strings)

[10462, 7246, 481, 307, 6164, 10185]
Swati will be mine!!!


### creating input - output pairs

In [30]:
with open('the-verdict.txt','r') as f:
  raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(enc_text[:50])

print(len(enc_text))

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11]
5145


#### let's remove first 50 tokens for making it more interesting

In [31]:
enc_sample = enc_text[50:]

#### one of the most easiest and intutive way to create input - output pairs for the next-word prediction task is the create two variables x for input and y for output which is just the input shifted by 1

#### context size represents size of input as well as how many predictions will we make in one iteration

In [32]:
context_size = 4 # length of input

# The context size of 4 means the model is trained to look at sequence of 4 words (or tokens)
# to predict the next token in the sequence

#The input x is the first 4 tokens [1, 2, 3, 4], and the target y is the next 4 tokens [2, 3, 4, 5]

x = enc_sample[:context_size]
y = enc_sample[1:context_size + 1]

In [33]:
print(x)
print(y)

[290, 4920, 2241, 287]
[4920, 2241, 287, 257]


Processing the inputs along with the targets, which are the inputs shifted by one position,
we can then create the next-word prediction tasks as

In [34]:
for i in range(1, context_size + 1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(context, "--->", desired)

[290] ---> 4920
[290, 4920] ---> 2241
[290, 4920, 2241] ---> 287
[290, 4920, 2241, 287] ---> 257


Everything left of the arrow (---->) refers to the input an LLM would receive, and the token
ID on the right side of the arrow represents the target token ID that the LLM is supposed to
predict.

For illustration purposes, let's repeat the previous code but convert the token IDs into

In [35]:
for i in range(1, context_size + 1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(tokenizer.decode(context), "--->", tokenizer.decode([desired]))

 and --->  established
 and established --->  himself
 and established himself --->  in
 and established himself in --->  a


####  we have created input-output pairs which we can use for training LLM later

### There's only one more task before we can turn the tokens into embeddings:implementing an efficient data loader that
iterates over the input dataset and returns the inputs and targets as PyTorch tensors, which
can be thought of as multidimensional arrays.

### In particular, we are interested in returning two tensors: an input tensor containing the
text that the LLM sees and a target tensor that includes the targets for the LLM to predict,

## Implementing a Data Loader

Step 1: Tokenize the entire text
    
Step 2: Use a sliding window to chunk the book into overlapping sequences of max_length

Step 3: Return the total number of rows in the dataset

Step 4: Return a single row from the dataset

In [36]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.output_ids = []

    # Tokenize the entire text
    token_ids = tokenizer.encode(txt, allowed_special={'<|endoftext|>'})

    # use a sliding window to chunk the book into overlapping sequence of maximum length
    for i in range(0, len(txt) - max_length, stride):
      input_chunk = token_ids[i:i + max_length]
      output_chunk = token_ids[i + 1: i + max_length + 1]

      self.input_ids.append(torch.tensor(input_chunk))
      self.output_ids.append(torch.tensor(output_chunk))


  def __len__(self):
    return len(self.input_ids)


  def __getitem__(self, idx):
    return self.input_ids[idx], self.output_ids[idx]





### The GPTDatasetV1 class in listing 2.5 is based on the PyTorch Dataset class.

It defines how individual rows are fetched from the dataset.

Each row consists of a number of
token IDs (based on a max_length) assigned to an input_chunk tensor.

The target_chunk
tensor contains the corresponding targets.

The following code will use the GPTDatasetV1 to load the inputs in batches via a PyTorch

Step 1: Initialize the tokenizer

Step 2: Create dataset

Step 3: drop_last=True drops the last batch if it is shorter than the specified batch_size to prevent loss spikes
during training

Step 4: The number of CPU processes to use for preprocessing

In [37]:
def create_dataloader_v1(txt, batch_size = 4, max_length = 256, stride = 128, shuffle=True, drop_last = True, num_workers = 0):


  # initialize the tokenizer
  tokenizer = tiktoken.get_encoding("gpt2")

  # creeate the dataset
  dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

  # create a dataloader
  dataloader = DataLoader(
      dataset,
      batch_size=batch_size,
      shuffle = shuffle,
      drop_last = drop_last,
      num_workers=num_workers
  )

  return dataloader

Let's test the dataloader with a batch size of 1 for an LLM with a context size of 4,

In [38]:
with open('the-verdict.txt','r') as f:
  raw_text = f.read()

Convert dataloader into a Python iterator to fetch the next entry via Python's built-in next() function

In [39]:
import torch

print("Pytorch versoin:", torch.__version__)

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

data_iter = iter(dataloader)

first_batch = next(data_iter)

print(first_batch)

Pytorch versoin: 2.11.0+cpu
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


The first_batch variable contains two tensors: the first tensor stores the input token IDs,
and the second tensor stores the target token IDs.

Since the max_length is set to 4, each of the two tensors contains 4 token IDs.

In [40]:
second_batch = next(data_iter)

print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


#### lets check with batch size greater than 8

In [41]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


### will now create vector embeddings

let's see how the token ID conversion works with a simple example with 4 token its

In [42]:
input_ids = torch.tensor([2, 3, 5, 1])

for the sake of simplicity lets take a small vocabulary of 6 size and output_dim = 4

In [43]:
vocab_s = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_s, output_dim)

In [44]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


lets now apply token id to extract the vector

In [45]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [46]:
print(embedding_layer(torch.tensor(input_ids)))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


/tmp/ipykernel_1536/3846183200.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(embedding_layer(torch.tensor(input_ids)))


### lets now create for the large size vocab (50257) and dim 256

In [47]:
vocab_s = 50257
output_dim = 256

In [48]:
embedding_layer = torch.nn.Embedding(vocab_s, output_dim)

### let's instansiate data loader now

In [49]:
max_length = 4
data_loader = create_dataloader_v1(
    raw_text, batch_size = 8, max_length = max_length, stride = max_length, shuffle = False
)


data_iter = iter(data_loader)
inputs, outputs = next(data_iter)

In [50]:
print(inputs)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])


In [51]:
print(outputs)

tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


### lets now convert the input tokens into corresponding vector embedding

In [52]:
token_embeddings = embedding_layer(inputs)
print(token_embeddings)
print(token_embeddings.shape)

tensor([[[ 0.4913,  1.1239,  1.4588,  ..., -0.3995, -1.8735, -0.1445],
         [ 0.4481,  0.2536, -0.2655,  ...,  0.4997, -1.1991, -1.1844],
         [-0.2507, -0.0546,  0.6687,  ...,  0.9618,  2.3737, -0.0528],
         [ 0.9457,  0.8657,  1.6191,  ..., -0.4544, -0.7460,  0.3483]],

        [[ 1.5460,  1.7368, -0.7848,  ..., -0.1004,  0.8584, -0.3421],
         [-1.8622, -0.1914, -0.3812,  ...,  1.1220, -0.3496,  0.6091],
         [ 1.9847, -0.6483, -0.1415,  ..., -0.3841, -0.9355,  1.4478],
         [ 0.9647,  1.2974, -1.6207,  ...,  1.1463,  1.5797,  0.3969]],

        [[-0.7713,  0.6572,  0.1663,  ..., -0.8044,  0.0542,  0.7426],
         [ 0.8046,  0.5047,  1.2922,  ...,  1.4648,  0.4097,  0.3205],
         [ 0.0795, -1.7636,  0.5750,  ...,  2.1823,  1.8231, -0.3635],
         [ 0.4267, -0.0647,  0.5686,  ..., -0.5209,  1.3065,  0.8473]],

        ...,

        [[-1.6156,  0.9610, -2.6437,  ..., -0.9645,  1.0888,  1.6383],
         [-0.3985, -0.9235, -1.3163,  ..., -1.1582, -1.13

### we now also need to create positional encodings

In [53]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [54]:
pos_embeddings = pos_embedding_layer(torch.arange(4))
print(pos_embeddings)
print(pos_embeddings.shape)

tensor([[ 1.7375, -0.5620, -0.6303,  ..., -0.2277,  1.5748,  1.0345],
        [ 1.6423, -0.7201,  0.2062,  ...,  0.4118,  0.1498, -0.4628],
        [-0.4651, -0.7757,  0.5806,  ...,  1.4335, -0.4963,  0.8579],
        [-0.6754, -0.4628,  1.4323,  ...,  0.8139, -0.7088,  0.4827]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 256])


### final step is creating input_embeddings by adding vector embeddings and positional embeddings

In [55]:
input_embeddings = token_embeddings + pos_embeddings

print(input_embeddings)
print(input_embeddings.shape)

tensor([[[ 2.2288,  0.5619,  0.8286,  ..., -0.6272, -0.2987,  0.8900],
         [ 2.0903, -0.4664, -0.0593,  ...,  0.9115, -1.0493, -1.6473],
         [-0.7158, -0.8304,  1.2494,  ...,  2.3952,  1.8773,  0.8051],
         [ 0.2703,  0.4029,  3.0514,  ...,  0.3595, -1.4548,  0.8310]],

        [[ 3.2835,  1.1749, -1.4150,  ..., -0.3281,  2.4332,  0.6924],
         [-0.2199, -0.9114, -0.1750,  ...,  1.5337, -0.1998,  0.1462],
         [ 1.5197, -1.4240,  0.4391,  ...,  1.0494, -1.4318,  2.3057],
         [ 0.2893,  0.8346, -0.1884,  ...,  1.9602,  0.8709,  0.8796]],

        [[ 0.9662,  0.0952, -0.4640,  ..., -1.0320,  1.6290,  1.7771],
         [ 2.4468, -0.2154,  1.4984,  ...,  1.8766,  0.5595, -0.1423],
         [-0.3856, -2.5393,  1.1556,  ...,  3.6157,  1.3267,  0.4944],
         [-0.2487, -0.5275,  2.0009,  ...,  0.2930,  0.5977,  1.3300]],

        ...,

        [[ 0.1219,  0.3991, -3.2740,  ..., -1.1921,  2.6637,  2.6728],
         [ 1.2438, -1.6436, -1.1101,  ..., -0.7464, -0.98

# Stage - 2 : ATTENTION MECHANISM

### We will now implement a simplified attention mechanism(without trainable weights) for strengthning our understanding

Simplified Attention Mechanism

lets do for a simple example first then will do for the whole input we have generated in previous part

In [56]:
import torch

inp = torch.tensor(
    [
        [0.43, 0.15, 0.89],  # your
        [0.55, 0.87, 0.66],  # journey
        [0.57, 0.85, 0.64],  # starts
        [0.22, 0.58, 0.33],  # with
        [0.77, 0.25, 0.10],  # one
        [0.05, 0.80, 0.55]   # step
    ]
)

##### we will find out context word for all words relative to every other word but for now let's do for journy to understand the process

#### and we will use the property that dot product finds relativity between different words

#### since we are focusing on only word for now we will call it query

In [57]:
query = inp[1]

# initializing an empty tensor for storing attention weights
attn_scores2 = torch.empty(inp.shape[0])


# looping in the input tensor to find dot product with every word
for i, xi in enumerate(inp):
  attn_scores2[i] = torch.dot(query, inp[i])

print(attn_scores2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


### but these scores are hard to analyze for a person so let's normalize them so that they can be intrepretated as probability and we can directly compare which word is most similar

#### We can normalize by dividing each value by total sum

In [58]:
attn_wts_norm1 = attn_scores2 / torch.sum(attn_scores2)

# straightforward normalizing by dividing each value by total sum
print(attn_wts_norm1)
print(attn_wts_norm1.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


### But there will be many limitations with this one which we have seen in logistic regression for multiple classes hence like that here also we switch to softmax normalization

In [59]:
def softmax_naive(x):
  return torch.exp(x) / torch.exp(x).sum(dim = 0)

attn_wts_norm2 = softmax_naive(attn_scores2)

print(attn_wts_norm2)
print(attn_wts_norm2.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


#### since sum is one we can now easily say  that the query(journey) is closest to journey and starts(word 2 and word 3) since they have highest attention scores respect to others

#### now to get the context vector for word journy we will multiply the calculate attention weights with the vector embeddings and sum all to get a final context vector

In [60]:
query = inp[1]

context_vec_2 = torch.zeros(query.shape)

for i, xi in enumerate(inp):
  context_vec_2 += xi * attn_wts_norm2[i]


print(context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


### this is the context vector for query with respect to all other tokens this we calculated just for understanding now lets calculate for all the tokens with respect to all tokens

In [61]:
n = inp.shape[0]
attn_scores = torch.empty(n, n)


for i,x_i in enumerate(inp):
  for j, x_j in enumerate(inp):
    attn_scores[i][j] = torch.dot(x_i,x_j)

print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


#### for calculating attention scores we used for loops but they are very slow but we can achieve the same result by multiplying inp x inp.T we can verify that by checking and result will also be same

In [62]:
attn_scores = inp @ inp.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


#### this is faster than for loops

### now we need to normalize each row

In [63]:
attn_weights = torch.softmax(attn_scores, dim = 1) # normalizing across each row hence dim = 1 as sum all columns for a row

print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


#### lets verify normalization

In [64]:
print(attn_weights.sum(dim = 1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


### lets now find the context vector matrix that contains context vectors for all the tokens/words

In [65]:
context_matrix = attn_weights @ inp

print(context_matrix)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


#### we could have done with for loops but that will be slower and this is faster and we can verify it that it will be exactly same even the dimension will be same as final context matrix must be 6 x 3 so that comes after multipling weights_matrx * input matrix = (6 x 6) X (6 x 3) = (6 x 3) which is the size of context_matrix also we can see for eg row1 of att_weights( att_weights of token 1 wrt to all token ) and whole inp matrx by row * row_wise multiplication of matrix each row is context vector when attn_weights of each word is multiplied by its vector

### now this simplified attention mechanism has some limitations that currently we found out context vector using attention weights of each token with respect to all tokens but that is only similar in symantic way, there can be words that are related to some word in the sentence but is not symantically similar in higher dimension so we can't jusy rely on simplified attention mechanism we need attention mechanism with weights

## self attention mechanism with trainable weights

### in this section we will implement self attention mechanism used in original transformer architecture, the GPT models and some famous LLM's. This self attention mechanism is also known as "Scaled dot-product attention".

In [66]:
import torch

inp = torch.tensor(
    [
        [0.43, 0.15, 0.89],  # your
        [0.55, 0.87, 0.66],  # journey
        [0.57, 0.85, 0.64],  # starts
        [0.22, 0.58, 0.33],  # with
        [0.77, 0.25, 0.10],  # one
        [0.05, 0.80, 0.55]   # step
    ]
)

#### like previously lets implement for only one token (journey) for understanding then will do for each token

#### lets convert the input to key, query and value matrices hence we need to multiply inp by Wk, Wq, Wv matrix of size 6x2

In [67]:
x_2 = inp[1]
d_in = inp.shape[1]
d_out = 2

### In models like gpt the d_in and d_out are mostly same but here we are taking different for illustration purpose

#### lets now define the Wk, Wq, Wv (weight) matrices for key, query and value that will later be optimized during training and we use them for generating key, query and value matrix

#### since it is trainable paramters so we initalize them like this and it will optimized later during training then we will put required_grad = True for now lets keep it false

In [68]:
torch.manual_seed(123)
W_Query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_Key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_Value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)

In [69]:
print(W_Query)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [70]:
print(W_Key)

Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])


In [71]:
print(W_Value)

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])


#### let's now compute key, query and value matrix for journey

In [72]:
query_2 = x_2 @ W_Query
key_2 = x_2 @ W_Key
value_2 = x_2 @ W_Value

In [73]:
print(query_2)

tensor([0.4306, 1.4551])


In [74]:
print(key_2)

tensor([0.4433, 1.1419])


In [75]:
print(value_2)

tensor([0.3951, 1.0037])


#### now we can calculate the query, keys and values matrix

In [76]:
query = inp @ W_Query
keys = inp @ W_Key
value = inp @ W_Value

In [77]:
print(query.shape)
print(keys.shape)
print(value.shape)

torch.Size([6, 2])
torch.Size([6, 2])
torch.Size([6, 2])


#### we can see from the output we have successfully projected input form 3-d space to a 2-d space

#### now we will forget the input vectors and will only use the query, key and value matrices

#### will do something similar like we did in simplified attention weights without weights there we use input itself and multiplied by input to find attention scores and then attention weights and then multiplied by input itself to calculate the final context vector

#### here we will use query as a query matrix to search and key matrix to find the attention scores of all inputs and then will multiply the attention weidhts with value to get final context vector

#### so like previously lets check for a single query then will do for whole matrix

In [81]:
query_2 = query[1]

attn_score_2 = query_2 @ keys.T

print(attn_score_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


#### this is basically attention scores of token2 (journey ) with all tokens

#### because query_2 is 1 x 2 and keys is 6 x 2 so we need to take transpose of keys to get the attention score vector of query_2

#### similarly lets find the attention score matrix for all querys

In [82]:
attention_scores = query @ keys.T
print(attention_scores)

tensor([[0.9231, 1.3545, 1.3241, 0.7910, 0.4032, 1.1330],
        [1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
        [1.2544, 1.8284, 1.7877, 1.0654, 0.5508, 1.5238],
        [0.6973, 1.0167, 0.9941, 0.5925, 0.3061, 0.8475],
        [0.6114, 0.8819, 0.8626, 0.5121, 0.2707, 0.7307],
        [0.8995, 1.3165, 1.2871, 0.7682, 0.3937, 1.0996]])


#### lets now convert these attention scores into attention weights

#### but this time we will not apply softmax directly this time we will scale the values by root(dimension of keys) then will apply softmax.

In [84]:
dim_keys = keys.shape[1]

attn_weights_2 = torch.softmax(attention_scores / dim_keys ** (0.5), dim = 1)

print(attn_weights_2)

tensor([[0.1551, 0.2104, 0.2059, 0.1413, 0.1074, 0.1799],
        [0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
        [0.1503, 0.2256, 0.2192, 0.1315, 0.0914, 0.1819],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.1206, 0.1769],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.1752],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])


In [85]:
print(attn_weights_2.sum(dim = 1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


### But why do we here divide by SQRT(dimension)?

Reason 1 : For stability in learning

The softmax function is sensitive to the magnitudes of its inputs. When the inputs are large, the difference between the exponential values of each input becomes much more pronounced. This causes the softmax output to become "Peaky", where the highest value recieves almost all the probability mass, and the rest recieves very little.

In attention mechanisms, particularly in transformers, if the dot product between query and key becomes too large (like multiplying by 8 in the example), the attention score becomes very large. This results in a very sharp softmax distribution, making the model confident in one particulay "key". Such sharp distributions can make learning unstable.

In [90]:
import torch

tensor = torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])


# apply softmax without scaling
softmax_result = torch.softmax(tensor, dim = -1) # -1 for last dimension as column is last dimension
print("Softmax before scaling:", softmax_result)

# multiply by 8 and then applying softmax
scaled_tensor = 8 * tensor
softmax_scaled_result = torch.softmax(scaled_tensor, dim = -1)
print("Softmax After scaling:", softmax_scaled_result)

Softmax before scaling: tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
Softmax After scaling: tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


#### we can see most of the weight is assingened to last component after scaling which is not good thats why we divide by SQRT(dim_keys)

### But why SQRT(dim_keys) ?

Reason - 2: To make the variance of dot product stable

The dot product of Q and K increases the variance because multiplying two random numbers.

The increase in dimension increase the variance

Diving by sqrt(dim) keeps variance close to 1

So thats the reason we divide it by SQRT(dim) before applying softmax and thats why it is called *** Scaled dot product attention ***

In [91]:
dim_keys = keys.shape[1]
attention_weights = torch.softmax(attention_scores / dim_keys ** 0.5, dim = 1)

print(attention_weights)

tensor([[0.1551, 0.2104, 0.2059, 0.1413, 0.1074, 0.1799],
        [0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
        [0.1503, 0.2256, 0.2192, 0.1315, 0.0914, 0.1819],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.1206, 0.1769],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.1752],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])


In [92]:
print(attention_weights.sum(dim = 1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


#### now lets calculate the context vectors of each input token by multiplying attention_weights x values matrix since attention weights is 6x6 and values is 6x2 we should get 6x2 as final context_matrix

In [94]:
context_matrix = attention_weights @ value

print(context_matrix)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]])


### Let's implement a class for doing all this as we will not write code seperately for each section we will create a class

In [99]:
import torch.nn as nn

class Self_Attention_v1(nn.Module):

  def __init__(self, in_dim, out_dim):
    super().__init__()
    self.W_query = nn.Parameter(torch.rand(in_dim, out_dim))
    self.W_key = nn.Parameter(torch.rand(in_dim, out_dim))
    self.W_value = nn.Parameter(torch.rand(in_dim, out_dim))


  def forward(self, x):
    keys = x @ self.W_query
    queries = x @ self.W_query
    values = x @ self.W_value

    attn_scores = queries @ keys.T
    attn_weights = torch.softmax(attn_scores / keys.shape[1] ** 0.5, dim = -1)

    context_vec = attn_weights @ values
    return context_vec

In [101]:
torch.manual_seed(123)

sa_v1 = Self_Attention_v1(d_in, d_out)
print(sa_v1.forward(inp))

tensor([[0.2997, 0.8094],
        [0.3067, 0.8265],
        [0.3063, 0.8256],
        [0.2947, 0.7960],
        [0.2925, 0.7900],
        [0.2991, 0.8077]], grad_fn=<MmBackward0>)


#### We can improve Self_Attention_V1 implementation further by utilizing Pytorch nn.Linear Layers

In [116]:
import torch.nn as nn

class Self_Attention_v2(nn.Module):

  def __init__(self, in_dim, out_dim, qkv_bias = False):
    super().__init__()
    self.W_query = nn.Linear(in_dim, out_dim, bias = qkv_bias )
    self.W_key = nn.Linear(in_dim, out_dim, bias = qkv_bias )
    self.W_value = nn.Linear(in_dim, out_dim, bias =qkv_bias )


  def forward(self, x):
    keys = self.W_query(x)
    queries = self.W_query(x)
    values = self.W_value(x)

    attn_scores = queries @ keys.T
    attn_weights = torch.softmax(attn_scores / keys.shape[1] ** 0.5, dim = -1)

    context_vec = attn_weights @ values
    return context_vec

In [117]:
torch.manual_seed(123)

sa_v2 = Self_Attention_v2(d_in, d_out)
print(sa_v2.forward(inp))

tensor([[-0.5287, -0.0976],
        [-0.5293, -0.1053],
        [-0.5293, -0.1052],
        [-0.5287, -0.1072],
        [-0.5287, -0.1038],
        [-0.5288, -0.1080]], grad_fn=<MmBackward0>)
