<a href="https://colab.research.google.com/github/Ekansh0801/Large-Language-Model/blob/main/Large_Language_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building Large Language Model from Scratch

## Stage - 1 : Data Preprocessing

In [28]:
# Loading the Dataset

with open('the-verdict.txt', 'r', encoding='utf-8') as file:
  raw_text = file.read()

print(len(raw_text))

20479


In [29]:
# Printing first 100 characters

print(raw_text[:100])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g


### Implementing Tokenization

#### step - 1: Creating Tokens

In [30]:
# Importing re library for tokenization purpose
import re

# splitting the text on any special character or -- or space
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)

# storing only non whitespace characters
preprocessed = [item.strip() for item in preprocessed if item.strip()]

print(len(preprocessed))

print(preprocessed[:100])

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--']


#### Step - 2: assigning token ID's

In [31]:
all_words = sorted(set(preprocessed))

vocab_size = len(all_words)
print(vocab_size)

1130


In [32]:
vocab = {token:integer for integer, token in enumerate(all_words)}
# print(vocab)

In [33]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


#### Implementing a Tokenizer class

In [34]:
class simpleTokenizerV1:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {value : key for key, value in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [token.strip() for token in preprocessed if token.strip()]

    ids = [self.str_to_int[token] for token in preprocessed]
    return ids

  def decode(self, ids):
    sentence = " ".join([self.int_to_str[id] for id in ids])
    sentence = re.sub(r'\s+([,.?!"()\'])', r'\1', sentence)
    return sentence

In [35]:
# check if the class is working succesfully

texty = """Well!--even through the prism of Hermia's tears I felt able to face the fact with equanimity.
Poor Jack Gisburn! The women had made him--it was fitting that they should mourn him.
Among his own sex fewer regrets were heard, and in his own trade hardly a murmur.
Professional jealousy? Perhaps. If it were, the honour of the craft was vindicated by little Claude Nutley,
who, in all good faith, brought out in the Burlington a very handsome "obituary" on Jack--one of those
showy articles stocked with random technicalities that I have heard (I won't say by whom) compared to
Gisburn's painting. And so--his resolve being apparently irrevocable--the discussion gradually
died out, and, as Mrs. Thwing had predicted, the price of "Gisburns" went up."""

tokenizer = simpleTokenizerV1(vocab)

ids = tokenizer.encode(texty)
print(ids)


[108, 0, 6, 399, 1007, 988, 795, 722, 50, 2, 850, 976, 53, 436, 117, 1016, 418, 988, 420, 1108, 395, 7, 80, 57, 38, 0, 93, 1112, 514, 654, 546, 6, 585, 1077, 444, 987, 994, 879, 687, 546, 7, 13, 549, 742, 872, 438, 829, 1088, 536, 5, 157, 568, 549, 742, 1026, 528, 115, 694, 7, 81, 589, 10, 79, 7, 54, 585, 1088, 5, 988, 553, 722, 988, 299, 1077, 1067, 241, 635, 26, 72, 5, 1097, 5, 568, 145, 500, 425, 5, 234, 738, 568, 988, 21, 115, 1065, 523, 1, 717, 1, 727, 57, 6, 729, 722, 1001, 884, 175, 927, 1108, 817, 977, 987, 53, 530, 536, 3, 53, 1113, 2, 970, 856, 241, 1099, 4, 281, 1016, 38, 2, 850, 748, 7, 14, 908, 6, 549, 838, 213, 165, 583, 6, 988, 345, 505, 337, 738, 5, 157, 5, 177, 67, 7, 100, 514, 786, 5, 988, 792, 722, 1, 39, 1, 1087, 1051, 7]


In [36]:
decoded_text = tokenizer.decode(ids)
print(decoded_text[:100])

Well! -- even through the prism of Hermia' s tears I felt able to face the fact with equanimity. Poo


In [37]:
unknown_str = "milk is healthy and is a good source of protien."

n_ids = tokenizer.encode(unknown_str)
print(n_ids)

KeyError: 'milk'

#### error because now we used an text with unknown words so it is not stored in the vocab hence error is thrown

#### Hence we will now extend unknown token and endoftext token also

In [48]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|unk|>", "<|endoftext|>"])

In [49]:
# updated vocab as it now includes unknown and endoftext also

vocab = { index:token for token, index in enumerate(all_tokens)}

for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|unk|>', 1130)
('<|endoftext|>', 1131)


### Updating tokenizer class

In [50]:
class simpleTokenizerV2:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {value : key for key, value in vocab.items()}

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [token.strip() for token in preprocessed if token.strip()]

    preprocessed = [item if item in self.str_to_int else '<|unk|>' for item in preprocessed]

    ids = [self.str_to_int[token] for token in preprocessed]
    return ids

  def decode(self, ids):
    sentence = " ".join([self.int_to_str[id] for id in ids])
    sentence = re.sub(r'\s+([,.?!"()\'])', r'\1', sentence)
    return sentence

#### checking the new tokenizer class

In [51]:
# unknown_str = "milk is healthy and is a good source of protien."

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

tokenizer2 = simpleTokenizerV2(vocab)
n_ids = tokenizer2.encode(text)
print(n_ids)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.
[1130, 5, 355, 1126, 628, 975, 10, 1131, 55, 988, 956, 984, 722, 988, 1130, 7]


In [52]:
dec_text = tokenizer2.decode(n_ids)
print(dec_text)

<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


### Byte Pair Encoding

In [53]:
pip install tiktoken

In [54]:
import importlib
import tiktoken

print("Tiktoken version:", importlib.metadata.version("tiktoken"))

Tiktoken version: 0.14.0


#### using the GPT-2 tokenizer

In [55]:
tokenizer = tiktoken.get_encoding("gpt2")

<div class="alert alert-block alert-success">
The usage of this tokenizer is similar to SimpleTokenizerV2 we implemented previously via
an encode method:</div>



In [56]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


<div class="alert alert-block alert-success">
We can then convert the token IDs back into text using the decode method, similar to our
SimpleTokenizerV2 earlier:</div>


In [57]:
strings = tokenizer.decode(integers)

print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


**Let us take another simple example to illustrate how the BPE tokenizer deals with unknown tokens**

In [58]:
integers = tokenizer.encode("Swati will be mine!!!")

print(integers)

strings = tokenizer.decode(integers)
print(strings)

[10462, 7246, 481, 307, 6164, 10185]
Swati will be mine!!!


### creating input - output pairs

In [59]:
with open('the-verdict.txt','r') as f:
  raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(enc_text[:50])

print(len(enc_text))

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11]
5145


#### let's remove first 50 tokens for making it more interesting

In [60]:
enc_sample = enc_text[50:]

#### one of the most easiest and intutive way to create input - output pairs for the next-word prediction task is the create two variables x for input and y for output which is just the input shifted by 1

#### context size represents size of input as well as how many predictions will we make in one iteration

In [61]:
context_size = 4 # length of input

# The context size of 4 means the model is trained to look at sequence of 4 words (or tokens)
# to predict the next token in the sequence

#The input x is the first 4 tokens [1, 2, 3, 4], and the target y is the next 4 tokens [2, 3, 4, 5]

x = enc_sample[:context_size]
y = enc_sample[1:context_size + 1]

In [62]:
print(x)
print(y)

[290, 4920, 2241, 287]
[4920, 2241, 287, 257]


Processing the inputs along with the targets, which are the inputs shifted by one position,
we can then create the next-word prediction tasks as

In [63]:
for i in range(1, context_size + 1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(context, "--->", desired)

[290] ---> 4920
[290, 4920] ---> 2241
[290, 4920, 2241] ---> 287
[290, 4920, 2241, 287] ---> 257


Everything left of the arrow (---->) refers to the input an LLM would receive, and the token
ID on the right side of the arrow represents the target token ID that the LLM is supposed to
predict.

For illustration purposes, let's repeat the previous code but convert the token IDs into

In [64]:
for i in range(1, context_size + 1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(tokenizer.decode(context), "--->", tokenizer.decode([desired]))

 and --->  established
 and established --->  himself
 and established himself --->  in
 and established himself in --->  a


####  we have created input-output pairs which we can use for training LLM later

### There's only one more task before we can turn the tokens into embeddings:implementing an efficient data loader that
iterates over the input dataset and returns the inputs and targets as PyTorch tensors, which
can be thought of as multidimensional arrays.

### In particular, we are interested in returning two tensors: an input tensor containing the
text that the LLM sees and a target tensor that includes the targets for the LLM to predict,

## Implementing a Data Loader

Step 1: Tokenize the entire text
    
Step 2: Use a sliding window to chunk the book into overlapping sequences of max_length

Step 3: Return the total number of rows in the dataset

Step 4: Return a single row from the dataset

In [65]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.output_ids = []

    # Tokenize the entire text
    token_ids = tokenizer.encode(txt, allowed_special={'<|endoftext|>'})

    # use a sliding window to chunk the book into overlapping sequence of maximum length
    for i in range(0, len(txt) - max_length, stride):
      input_chunk = token_ids[i:i + max_length]
      output_chunk = token_ids[i + 1: i + max_length + 1]

      self.input_ids.append(torch.tensor(input_chunk))
      self.output_ids.append(torch.tensor(output_chunk))


  def __len__(self):
    return len(self.input_ids)


  def __getitem__(self, idx):
    return self.input_ids[idx], self.output_ids[idx]





### The GPTDatasetV1 class in listing 2.5 is based on the PyTorch Dataset class.

It defines how individual rows are fetched from the dataset.

Each row consists of a number of
token IDs (based on a max_length) assigned to an input_chunk tensor.

The target_chunk
tensor contains the corresponding targets.

The following code will use the GPTDatasetV1 to load the inputs in batches via a PyTorch

Step 1: Initialize the tokenizer

Step 2: Create dataset

Step 3: drop_last=True drops the last batch if it is shorter than the specified batch_size to prevent loss spikes
during training

Step 4: The number of CPU processes to use for preprocessing

In [66]:
def create_dataloader_v1(txt, batch_size = 4, max_length = 256, stride = 128, shuffle=True, drop_last = True, num_workers = 0):


  # initialize the tokenizer
  tokenizer = tiktoken.get_encoding("gpt2")

  # creeate the dataset
  dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

  # create a dataloader
  dataloader = DataLoader(
      dataset,
      batch_size=batch_size,
      shuffle = shuffle,
      drop_last = drop_last,
      num_workers=num_workers
  )

  return dataloader

Let's test the dataloader with a batch size of 1 for an LLM with a context size of 4,

In [67]:
with open('the-verdict.txt','r') as f:
  raw_text = f.read()

Convert dataloader into a Python iterator to fetch the next entry via Python's built-in next() function

In [68]:
import torch

print("Pytorch versoin:", torch.__version__)

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

data_iter = iter(dataloader)

first_batch = next(data_iter)

print(first_batch)

Pytorch versoin: 2.11.0+cpu
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


The first_batch variable contains two tensors: the first tensor stores the input token IDs,
and the second tensor stores the target token IDs.

Since the max_length is set to 4, each of the two tensors contains 4 token IDs.

In [69]:
second_batch = next(data_iter)

print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


#### lets check with batch size greater than 8

In [70]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


### will now create vector embeddings

let's see how the token ID conversion works with a simple example with 4 token its

In [72]:
input_ids = torch.tensor([2, 3, 5, 1])

for the sake of simplicity lets take a small vocabulary of 6 size and output_dim = 4

In [73]:
vocab_s = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_s, output_dim)

In [78]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


lets now apply token id to extract the vector

In [79]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [81]:
print(embedding_layer(torch.tensor(input_ids)))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


/tmp/ipykernel_2630/3846183200.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(embedding_layer(torch.tensor(input_ids)))


### lets now create for the large size vocab (50257) and dim 256

In [82]:
vocab_s = 50257
output_dim = 256

In [83]:
embedding_layer = torch.nn.Embedding(vocab_s, output_dim)

### let's instansiate data loader now

In [86]:
max_length = 4
data_loader = create_dataloader_v1(
    raw_text, batch_size = 8, max_length = max_length, stride = max_length, shuffle = False
)


data_iter = iter(data_loader)
inputs, outputs = next(data_iter)

In [87]:
print(inputs)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])


In [88]:
print(outputs)

tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


### lets now convert the input tokens into corresponding vector embedding

In [90]:
token_embeddings = embedding_layer(inputs)
print(token_embeddings)
print(token_embeddings.shape)

tensor([[[ 0.4913,  1.1239,  1.4588,  ..., -0.3995, -1.8735, -0.1445],
         [ 0.4481,  0.2536, -0.2655,  ...,  0.4997, -1.1991, -1.1844],
         [-0.2507, -0.0546,  0.6687,  ...,  0.9618,  2.3737, -0.0528],
         [ 0.9457,  0.8657,  1.6191,  ..., -0.4544, -0.7460,  0.3483]],

        [[ 1.5460,  1.7368, -0.7848,  ..., -0.1004,  0.8584, -0.3421],
         [-1.8622, -0.1914, -0.3812,  ...,  1.1220, -0.3496,  0.6091],
         [ 1.9847, -0.6483, -0.1415,  ..., -0.3841, -0.9355,  1.4478],
         [ 0.9647,  1.2974, -1.6207,  ...,  1.1463,  1.5797,  0.3969]],

        [[-0.7713,  0.6572,  0.1663,  ..., -0.8044,  0.0542,  0.7426],
         [ 0.8046,  0.5047,  1.2922,  ...,  1.4648,  0.4097,  0.3205],
         [ 0.0795, -1.7636,  0.5750,  ...,  2.1823,  1.8231, -0.3635],
         [ 0.4267, -0.0647,  0.5686,  ..., -0.5209,  1.3065,  0.8473]],

        ...,

        [[-1.6156,  0.9610, -2.6437,  ..., -0.9645,  1.0888,  1.6383],
         [-0.3985, -0.9235, -1.3163,  ..., -1.1582, -1.13

### we now also need to create positional encodings

In [91]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [96]:
pos_embeddings = pos_embedding_layer(torch.arange(4))
print(pos_embeddings)
print(pos_embeddings.shape)

tensor([[-0.6303, -0.4848, -0.1366,  ...,  1.0345, -0.5012,  1.1045],
        [ 0.2062,  0.6078,  0.7187,  ..., -0.4628, -0.2319,  1.1980],
        [ 0.5806, -1.3846,  0.3266,  ...,  0.8579,  0.5059,  1.0243],
        [ 1.4323,  0.2217,  0.8599,  ...,  0.4827,  0.8459,  1.3038]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 256])


### final step is creating input_embeddings by adding vector embeddings and positional embeddings

In [97]:
input_embeddings = token_embeddings + pos_embeddings

print(input_embeddings)
print(input_embeddings.shape)

tensor([[[-0.1390,  0.6390,  1.3222,  ...,  0.6350, -2.3747,  0.9599],
         [ 0.6543,  0.8614,  0.4532,  ...,  0.0369, -1.4310,  0.0136],
         [ 0.3299, -1.4393,  0.9953,  ...,  1.8197,  2.8795,  0.9715],
         [ 2.3781,  1.0874,  2.4790,  ...,  0.0283,  0.0999,  1.6521]],

        [[ 0.9158,  1.2520, -0.9214,  ...,  0.9341,  0.3572,  0.7624],
         [-1.6560,  0.4164,  0.3375,  ...,  0.6591, -0.5815,  1.8070],
         [ 2.5653, -2.0329,  0.1851,  ...,  0.4738, -0.4297,  2.4721],
         [ 2.3971,  1.5190, -0.7608,  ...,  1.6290,  2.4256,  1.7007]],

        [[-1.4016,  0.1724,  0.0297,  ...,  0.2302, -0.4470,  1.8471],
         [ 1.0107,  1.1125,  2.0109,  ...,  1.0020,  0.1778,  1.5185],
         [ 0.6601, -3.1482,  0.9016,  ...,  3.0402,  2.3289,  0.6608],
         [ 1.8590,  0.1569,  1.4285,  ..., -0.0382,  2.1524,  2.1511]],

        ...,

        [[-2.2458,  0.4762, -2.7803,  ...,  0.0701,  0.5877,  2.7428],
         [-0.1923, -0.3157, -0.5976,  ..., -1.6210, -1.36